---
title: 'Final Project: Data Wrangling'
output:
  pdf_document: default
  html_document: default
---

```{r Setting Up Environment}
getwd()
library(tidyverse)
```

```{r Only Big Island Sites}
CoverClass_Data <- 
  read.csv("Data/Raw/PACN_EIPS_Cover_Class_Data.csv", stringsAsFactors = FALSE)

CoverClass_BigIsland <- 
  CoverClass_Data %>%
  filter(custom_samplingFrame %in% c("Mauna Loa", "Olaa", "Nahuku / East Rift"))

unique(CoverClass_BigIsland$custom_samplingFrame)
```

```{r Single Date Column}
BigIsland_Clean <- 
  CoverClass_BigIsland %>%
  select(-custom_startDate, -custom_eventTimeStart, -custom_eventTimeEnd) %>%
  rename(Date = custom_endDate)
```

```{r Processed with only 10 chosen variables and remove NA}
BigIsland_Processed <- BigIsland_Clean %>%
  select(custom_plantCommunity, custom_samplingFrame, decimalLatitude, decimalLongitude, geodeticDatum, Date, custom_speciesCode, scientificName, vernacularName, custom_lifeForm) %>%
  drop_na()

colnames(BigIsland_Processed) <- c("Plant_Community", "Sampling_Frame", "Decimal_Latitude", "Decimal_Longitude", "GeodeticDatum", "Date", "Species_Code", "Scientific_Name", "Vernacular_Name", "Life_Form")

BigIsland_Processed$Date <- ymd(BigIsland_Processed$Date)
class(BigIsland_Processed$Date)

write.csv(BigIsland_Processed, "Data/Processed/BigIsland_Processed.csv", row.names = FALSE)

```

```{r Mapping Exploration}
library(sf)

hawaiitheme <- 
   theme(
    plot.background = element_rect(fill = "white"),
    legend.background = element_rect(fill = "white"),
    legend.title = element_text(color = "black", 
                                face = "bold",
                                family = "serif"),
    legend.text = element_text(color = "black",
                               family = "serif"),
    panel.background = element_rect(fill = "cyan3"),
    panel.grid.major = element_line(color = "lightblue2"),
    panel.grid.minor = element_line(color = "lightblue2"),
    plot.title = element_text(face = "bold",
                              size = 16,
                              color = "black",
                              family = "serif"),
    axis.title.x  = element_text(
                               face = "italic", 
                               size = 8, 
                               color = "black",
                               family = "serif"),
    axis.title.y = element_text( 
                               face = "italic", 
                               size = 8, 
                               color = "black",
                               family = "serif"))
  
hawaii.counties <- st_read("Data/Raw/cb_2018_us_county_20m.shp")%>%
filter(STATEFP == 15 )

big_island <- hawaii.counties %>% 
  filter(NAME == "Hawaii")


sites_sf <- st_as_sf(BigIsland_Processed, coords = c("Decimal_Longitude","Decimal_Latitude"), crs = 4326) 

ggplot() +
  geom_sf(data=big_island, fill="palegreen",
          color="forestgreen") +
  geom_sf(data = sites_sf, 
          aes(color = BigIsland_Processed$Sampling_Frame), 
          size = 2) +
  hawaiitheme+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(title = "Sampling Locations on the Big Island",
       color = "Sampling Sites")
```
```{r Mauna Loa Closer Look}

MaunaLoa_subset <- 
  BigIsland_Processed%>%
  filter(Sampling_Frame == "Mauna Loa")%>%
  filter(Date == "2011-05-19")

maunaloa_sites_sf <- st_as_sf(MaunaLoa_subset, coords = c("Decimal_Longitude","Decimal_Latitude"), crs = 4326) 

```

```{r Specific Species Mapping Exploration}
HiloGrass_subset <- 
  BigIsland_Processed%>%
  filter(Vernacular_Name == "Hilo grass")

sites_sf <- st_as_sf(HiloGrass_subset, coords = c("Decimal_Longitude","Decimal_Latitude"), crs = 4326) 

ggplot() +
  geom_sf(data=big_island, fill="palegreen",
          color="forestgreen") +
  geom_sf(data = sites_sf, 
          aes(color = HiloGrass_subset$Sampling_Frame), 
          size = 2) +
  hawaiitheme+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(title = "Hilo Grass Records in Sampling Sites",
       color = "Sampling Sites")

#could make maps of species common in 2 of 3 sites, a map of one species year by year in one sampling site, etc.
#difficult to map different species at one site becuase all have the same transect coordinates given the sampling date. 
```








