---
title: "BigIsland_Analysis"
author: "Elizabeth Miles-Flynn"
date: "2025-12-03"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(here)

getwd()
here()

BigIsland_Processed <- read.csv(
  here("Data", "Processed", "BigIsland_Processed.csv"),
  stringsAsFactors = FALSE)
```

```{r Research Question 1 - Compare Overall Species Richness, echo = FALSE}
#Note: in the title names I added "\n" to create new line breaks to prevent text from disappearing from the screen, so they are NOT typos
Invasive_Richness <- ggplot(BigIsland_Processed, aes(x = Sampling_Frame, fill = Sampling_Frame)) +
 geom_bar() +
  labs(
    title = "Overall Invasive Species Richness at Each Site\non the Big Island of Hawaii",
    subtitle = "Wet Forest in Blue | Subalpine Shrubland in Orange",
    x = "Site Name",
    y = "Species Count"
  ) +
  scale_fill_manual(values = c("Mauna Loa" = "orange2",
                    "Olaa" = "steelblue",
                    "Nahuku / East Rift" = "lightblue"),
                    guide = "none")
  
print(Invasive_Richness)
```
```{r Research Question 1 - Compare Species Richness by Life Form type... sucession???, echo = FALSE}

Invasive_Richness_Site <- ggplot(BigIsland_Processed, aes(x = Sampling_Frame, fill = Life_Form)) +
 geom_bar(position = "stack") +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Invasive Species Richness by Life Form\nat Each Site on the Big Island of Hawaii",
    x = "Site Name",
    y = "Species Count",
    fill = "Life Form\nCategory",
    )
  
print(Invasive_Richness_Site)

Invasive_Richness_Type1 <- ggplot(BigIsland_Processed, aes(x = Life_Form, fill = Sampling_Frame)) +
 geom_bar(position = "dodge") +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Invasive Species Richness by Life Form at Each Site\non the Big Island of Hawaii",
    subtitle = "Wet Forest in Blue | Subalpine Shrubland in Orange",
    x = "Life Form Category",
    y = "Species Count",
    fill = "Site Name",
    ) +
   scale_fill_manual(values = c("Mauna Loa" = "orange2",
                    "Olaa" = "steelblue",
                    "Nahuku / East Rift" = "lightblue"))
  
print(Invasive_Richness_Type1)

Invasive_Richness_Type2 <- ggplot(BigIsland_Processed, aes(x = Life_Form, fill = Sampling_Frame)) +
 geom_bar(position = "stack") +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Invasive Species Richness by Life Form at Each Site\non the Big Island of Hawaii",
    subtitle = "Wet Forest in Blue | Subalpine Shrubland in Orange",
    x = "Life Form Category",
    y = "Species Count",
    fill = "Site Name",
    ) +
   scale_fill_manual(values = c("Mauna Loa" = "orange2",
                    "Olaa" = "steelblue",
                    "Nahuku / East Rift" = "lightblue"))
  
print(Invasive_Richness_Type2)
```
```{r Research Question 1 - Compare Species Abundance, echo = FALSE}
############### TREE ###############
Tree_only <- BigIsland_Processed %>%
  filter(Life_Form == "Tree")

Tree_Abundance <- ggplot(Tree_only, aes(x = Species_Code, fill = Species_Code)) +
  geom_bar() +
  facet_wrap(~ Sampling_Frame, ncol = 1) +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Tree Species Abundance at Each Site on the Big Island of Hawaii",
    x = "Tree Species Type",
    y = "Species Count"
  )+
  theme(legend.position = "none")

print(Tree_Abundance)

############### FERN ###############
Fern_only <- BigIsland_Processed %>%
  filter(Life_Form == "Fern")

Fern_Abundance <- ggplot(Fern_only, aes(x = Species_Code, fill = Species_Code)) +
  geom_bar() +
  facet_wrap(~ Sampling_Frame, ncol = 1) +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Fern Species Abundance at Each Site on the Big Island of Hawaii",
    x = "Fern Species Type",
    y = "Species Count"
  ) +
  theme(legend.position = "none")

print(Fern_Abundance)

############### GRASS ############### Note: Too many species... looks messy
Grass_only <- BigIsland_Processed %>%
  filter(Life_Form == "Grass")

Grass_Abundance <- ggplot(Grass_only, aes(x = Species_Code, fill = Species_Code)) +
  geom_bar() +
  facet_wrap(~ Sampling_Frame, ncol = 1) +
  labs(
    title = "Grass Species Abundance at Each Site on the Big Island of Hawaii",
    x = "Grass Species Type",
    y = "Species Count"
  ) +
  theme(legend.position = "none")

print(Grass_Abundance)

############### Herb ############### Note: too many species... looks messy
Herb_only <- BigIsland_Processed %>%
  filter(Life_Form == "Herb")

Herb_Abundance <- ggplot(Herb_only, aes(x = Species_Code, fill = Species_Code)) +
  geom_bar() +
  facet_wrap(~ Sampling_Frame, ncol = 1) +
  labs(
    title = "Herb Species Abundance at Each Site on the Big Island of Hawaii",
    x = "Herb Species Type",
    y = "Species Count"
  ) +
  theme(legend.position = "none")

print(Herb_Abundance)

############### SEDGE ###############
Sedge_only <- BigIsland_Processed %>%
  filter(Life_Form == "Sedge")

Sedge_Abundance <- ggplot(Sedge_only, aes(x = Species_Code, fill = Species_Code)) +
  geom_bar() +
  facet_wrap(~ Sampling_Frame, ncol = 1) +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Sedge Species Abundance at Each Site on the Big Island of Hawaii",
    x = "Sedge Species Type",
    y = "Species Count"
  ) +
  theme(legend.position = "none")

print(Sedge_Abundance)

############### Shrub ############### Note: Mauna Loa looks empty in the bar graph, but if you look at sub-dataset "Shrub_only" theres ONE specie listed under Mauna Loa
Shrub_only <- BigIsland_Processed %>%
  filter(Life_Form == "Shrub")

Shrub_Abundance <- ggplot(Shrub_only, aes(x = Species_Code, fill = Species_Code)) +
  geom_bar() +
  facet_wrap(~ Sampling_Frame, ncol = 1) +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Shrub Species Abundance at Each Site on the Big Island of Hawaii",
    x = "Shrub Species Type",
    y = "Species Count"
  ) +
  theme(legend.position = "none")

print(Shrub_Abundance)

############### TREE FERN ###############
Tree.Fern_only <- BigIsland_Processed %>%
  filter(Life_Form == "Tree Fern")

Tree.Fern_Abundance <- ggplot(Tree.Fern_only, aes(x = Species_Code, fill = Species_Code)) +
  geom_bar() +
  facet_wrap(~ Sampling_Frame, ncol = 1) +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Tree Fern Species Abundance at Each Site on the Big Island of Hawaii",
    x = "Tree Fern Species Type",
    y = "Species Count"
  ) +
  theme(legend.position = "none")

print(Tree.Fern_Abundance)

############### VINE ###############
Vine_only <- BigIsland_Processed %>%
  filter(Life_Form == "Vine")

Vine_Abundance <- ggplot(Vine_only, aes(x = Species_Code, fill = Species_Code)) +
  geom_bar() +
  facet_wrap(~ Sampling_Frame, ncol = 1) +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Vine Species Abundance at Each Site on the Big Island of Hawaii",
    x = "Vine Species Type",
    y = "Species Count"
  ) +
  theme(legend.position = "none")

print(Vine_Abundance)
```

```{r Research Question 1 - One-way ANOVA statistical analysis, echo = FALSE}
### Struggling to find a statistical test that will best represent our data since we have "character" type data and not "numeric". This can be achieved by calculating the sum count of species richness for each site?

#ANOVA test on overall richness between sites. Ola'a has significantly higher invasive species richness in comparison to Mauna Loa. 
Richness <- BigIsland_Clean %>%
  group_by(custom_samplingFrame, custom_transectNumber) %>%
  summarise(Richness = n_distinct(vernacularName), .groups = "drop")

anova_model <- aov(Richness ~ custom_samplingFrame, data = Richness)
summary(anova_model)

TukeyHSD(anova_model)

#ANOVA test on  number of Life Forms 
VegTypeANOVA <- BigIsland_Clean %>%
  group_by(custom_samplingFrame, custom_transectNumber) %>%
  summarise(Diversity = n_distinct(custom_lifeForm), .groups = "drop")

anova_model2 <- aov(Diversity ~ custom_samplingFrame, data = VegTypeANOVA)
summary(anova_model2)

TukeyHSD(anova_model2)

#findings: all statistically significant
##mauna loa has the least structural diversity (i.e tree + shrub + fern + grass (richness score of 4) versus just grass + shrub (richness score of 2))
###nahuku east rift is moderately diverse
###olaa is the is the most diverse in number of life form types at a given sampling point
```

```{r Research Question 1 - Dominance and Spread, echo = FALSE}
### not really sure how to represent this... spatial???

#visual comparison of one site to another, or points where we saw life form type (could do year to year comparison)
```

```{r Research Question 2 - time series analysis, echo = FALSE}
library(zoo); library(trend)

Richness_by_Year <- BigIsland_Processed %>%
  mutate(Year = year(Date)) %>%
  group_by(Year, Sampling_Frame) %>%
  summarise(TotalSpecies = n_distinct(Species_Code), .groups = "drop")

#add linear interpolation
Richness_by_Year <- Richness_by_Year %>%
  arrange(Year) %>%
  group_by(Sampling_Frame) %>%
  mutate(TotalSpecies = zoo::na.approx(TotalSpecies, x = Year, na.rm = FALSE)) %>%
  ungroup()

invasion.time.plot <- ggplot (Richness_by_Year, aes(x = Year, y = TotalSpecies, color = Sampling_Frame)) +
  geom_line(size = 1.5) +
  geom_point(size = 3) +
  geom_smooth (method = "lm", se = FALSE, col = "coral3") +
  facet_wrap( ~ Sampling_Frame, ncol = 1) +
  scale_x_continuous(breaks = seq(2010, 2023, by = 2))+
  labs(
    title = "2010 to 2023 Detection of Invasive Species for Each Site\non the Big Island of Hawaii",
    x = "Year",
    y = "Total Invasive Species Count",
    color = "Site Name"
  ) +
  scale_color_manual(values = c("Mauna Loa" = "orange2",
                    "Olaa" = "steelblue",
                    "Nahuku / East Rift" = "lightblue"))

print(invasion.time.plot)
```

